---
name: Run CI checks

on:
  pull_request:
    types: "**"
    branches: "**"
  pull_request_review:
    types: "**"
    branches: "**"

jobs:
  steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}

  
# jobs:
#   TriggerWorkfows:
#     uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
#     with:
#       EVENT: "${{ toJSON(github.event) }}"

