---
name: Run CI checks

on:
  pull_request:
    types: "**"
    branches: "**"
  pull_request_review:
    types: "**"
    branches: "**"
env:
  event_github: ${{ toJSON(github) }}

  
jobs:
  TriggerWorkfows:
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ env.event_github }} 