---
  name: Run CI checks
  
  on:
    pull_request:
      types: "**"
      branches: "**"
    pull_request_review:
      types: "**"
      branches: "**"
  jobs:
    TriggerWorkfows:
      uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.1
      with:
        EVENT: ${{ toJson(github.event) }}
  